[config]

[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "wipe"]
set = true


[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.mako]
input_path = './templates/mako-colors.conf'
output_path = '~/.config/mako/config'
post_hook = 'pkill -SIGUSR1 mako'

[templates.btop]
input_path = './templates/btop-colors.conf'
output_path = '~/.config/btop/themes/matugen.conf'

[templates.quickshell]
input_path = './templates/quickshell-colors'
output_path = '~/.config/quickshell/colors.js'
post_hook = 'pkill quickshell && quickshell &'
